name: Terraform Preview

on:
  pull_request:

jobs:
  preview:
    name: Plan Terraform changes in changed Terramate stacks
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2
        with:
         use_wrapper: "false"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
          terraform_wrapper: false

      - name: Check Terramate formatting
        run: terramate fmt --check

      - name: Check Terraform formatting
        run: terraform fmt -recursive -check -diff

      - name: List changed stacks
        id: list
        run: |
          terramate list --changed > changed-stacks.txt
          echo "CHANGEDSTACKS=$(cat changed-stacks.txt)" >> $GITHUB_ENV

      - name: Initialize Terraform in changed stacks
        if: steps.list.outputs.CHANGEDSTACKS != ''
        id: init
        run: |
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
          terramate run \
           --parallel 1 \
           --changed \
           -- \
           terraform init -lock-timeout=5m

      - name: Validate Terraform configuration in changed stacks
        if: steps.list.outputs.CHANGEDSTACKS != ''
        id: validate
        run: |
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
          terramate run \
            --parallel 5 \
            --changed \
            -- \
            terraform validate

      - name: Plan Terraform changes in changed stacks
        if: steps.list.outputs.CHANGEDSTACKS != ''
        id: plan
        run: |
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
          terramate run \
            --parallel 5 \
            --changed \
            --sync-preview \
            --terraform-plan-file=out.tfplan \
            --continue-on-error \
            -- \
            terraform plan -out out.tfplan -detailed-exitcode -lock=false
        env:
          GITHUB_TOKEN: ${{ github.token }}
